"""empty message

Revision ID: d069215716d3
Revises: ea50768eaaf3
Create Date: 2018-06-07 15:00:55.231031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd069215716d3'
down_revision = 'ea50768eaaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('photo_1', sa.String(200), nullable=True))
    op.add_column('t_user', sa.Column('photo_2', sa.String(200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'photo_2')
    op.drop_column('t_user', 'photo_1')
    # ### end Alembic commands ###
